In [33]:
# Import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
# Check the current working directory

import os

os.getcwd()

'C:\\Users\\miked\\Desktop\\Documents\\Data Analysis Projects\\Pharma Drug Spending Analysis with PowerBI\\data cleaning'

In [22]:
# Set the working directory

os.chdir(r"C:\Users\miked\Desktop\Documents\Data Analysis Projects\Pharma Drug Spending Analysis with PowerBI")

In [23]:
# Load the dataset

mydata = pd.read_csv(r"C:\Users\miked\Desktop\Documents\Data Analysis Projects\Pharma Drug Spending Analysis with PowerBI\dataset\pharma_spendings_raw.csv",
                     encoding="latin1")

In [34]:
# Display the head of the dataset

mydata.head(5)

,country,year,percentage_health_exp,percentage_gdp,usd_per_capita,total_expenditure
0,Australia,1971,15.992,0.726,33.990,439.73
1,Australia,1972,15.091,0.685,34.184,450.44
2,Australia,1973,15.117,0.681,37.956,507.85
3,Australia,1974,14.771,0.754,45.338,622.17
4,Australia,1975,11.849,0.682,44.363,616.34

In [25]:
# Inspect the dataset structure

mydata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1341 entries, 0 to 1340
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   LOCATION     1341 non-null   object
 1   TIME         1341 non-null   int64
 2   PC_HEALTHXP  1341 non-null   float64
 3   PC_GDP       1341 non-null   float64
 4   USD_CAP      1341 non-null   float64
 5   TOTAL_SPEND  1341 non-null   float64
dtypes: float64(4), int64(1), object(1)
memory usage: 63.0+ KB

In [26]:
mydata.shape

(1341, 6)

In [35]:
mydata.describe()

,year,percentage_health_exp,percentage_gdp,usd_per_capita,total_expenditure
count,1341.000000,1341.000000,1341.000000,1341.000000,1341.000000
mean,2001.134228,16.632877,1.215524,338.278398,14439.322088
std,14.093659,6.613320,0.479568,226.158326,43259.358895
min,1970.000000,5.545000,0.207000,3.628000,5.810000
25%,1990.000000,11.849000,0.802000,144.592000,756.280000
50%,2004.000000,15.238000,1.187000,317.795000,2786.190000
75%,2013.000000,20.580000,1.524000,496.858000,8794.360000
max,2022.000000,40.239000,2.870000,1432.309000,475596.740000

In [28]:
mydata = mydata.rename(columns={
    'LOCATION': 'country',
    'TIME': 'year',
    'PC_HEALTHXP': 'percentage_health_exp',
    'PC_GDP': 'percentage_gdp',
    'USD_CAP': 'usd_per_capita',
    'TOTAL_SPEND': 'total_expenditure'
})

In [29]:
mydata['country'].value_counts()

country
CAN    53
KOR    53
ISL    53
SWE    52
NOR    52
FIN    52
DEU    51
NLD    51
AUS    50
IRL    47
BEL    47
PRT    45
LUX    45
DNK    43
ESP    38
JPN    38
FRA    36
GBR    36
USA    35
ITA    35
GRC    34
CZE    32
AUT    32
HUN    28
NZL    24
MEX    23
EST    23
SVK    23
SVN    20
POL    20
ROU    19
CYP    19
LVA    18
LTU    18
BGR    16
ISR    15
CHE    12
HRV    11
CRI    11
TUR    11
MLT     7
BRA     5
COL     5
CHL     3
Name: count, dtype: int64

In [30]:
country_names = {
    'AUS': 'Australia',
    'AUT': 'Austria',
    'BEL': 'Belgium',
    'BGR': 'Bulgaria',
    'BRA': 'Brazil',
    'CAN': 'Canada',
    'CHE': 'Switzerland',
    'CHL': 'Chile',
    'COL': 'Colombia',
    'CRI': 'Costa Rica',
    'CYP': 'Cyprus',
    'CZE': 'Czech Republic',
    'DEU': 'Germany',
    'DNK': 'Denmark',
    'ESP': 'Spain',
    'EST': 'Estonia',
    'FIN': 'Finland',
    'FRA': 'France',
    'GBR': 'United Kingdom',
    'GRC': 'Greece',
    'HRV': 'Croatia',
    'HUN': 'Hungary',
    'IRL': 'Ireland',
    'ISL': 'Iceland',
    'ISR': 'Israel',
    'ITA': 'Italy',
    'JPN': 'Japan',
    'KOR': 'South Korea',
    'LTU': 'Lithuania',
    'LUX': 'Luxembourg',
    'LVA': 'Latvia',
    'MLT': 'Malta',
    'MEX': 'Mexico',
    'NLD': 'Netherlands',
    'NOR': 'Norway',
    'NZL': 'New Zealand',
    'POL': 'Poland',
    'PRT': 'Portugal',
    'ROU': 'Romania',
    'SVK': 'Slovakia',
    'SVN': 'Slovenia',
    'SWE': 'Sweden',
    'TUR': 'Turkey',
    'USA': 'United States'
}

mydata['country'] = mydata['country'].replace(country_names)

In [31]:
mydata.isna().sum()

country                  0
year                     0
percentage_health_exp    0
percentage_gdp           0
usd_per_capita           0
total_expenditure        0
dtype: int64

In [32]:
mydata.duplicated().sum()

np.int64(0)

In [36]:
mydata.to_csv("pharma_spendings_clean.csv", index=False)